const ActionTypes = {
  STORE_UPDATE_INIT_INFO: 'STORE_UPDATE_INIT_INFO',
  FETCH_INIT_INFO_SUCCESS: 'FETCH_INIT_INFO_SUCCESS',
  STORE_UPDATE_IS_VIDEO_LOADED_SUCCESS: 'STORE_UPDATE_IS_VIDEO_LOADED_SUCCESS',
};

export default ActionTypes;
