/*
auto-generated by: https://github.com/react-spring/gltfjsx
author: facerate (https://sketchfab.com/facerate)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/elven-ranger-statue-71aec2d9f7724ae09992435ce8ff7258
title: Elven ranger statue
*/

import * as THREE from 'three'
import React, { useEffect, useRef } from 'react'
import { useLoader, useFrame } from 'react-three-fiber'
import { GLTFLoader } from 'three/examples/jsm/loaders/GLTFLoader'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials, animations } = useLoader(GLTFLoader, '/scene.glb')

  return (
    <group ref={group} {...props} dispose={null}>
      <scene name="OSG_Scene">
        <group name="RootNode_(gltf_orientation_matrix)" rotation={[-Math.PI / 2, 0, 0]}>
          <group name="RootNode_(model_correction_matrix)">
            <group name="elfOBJcleanermaterialmergergles">
              <mesh material={materials.material_0} geometry={nodes.mesh_0.geometry} name="mesh_0" />
              <mesh material={materials.material_0} geometry={nodes.mesh_1.geometry} name="mesh_1" />
              <mesh material={materials.material_0} geometry={nodes.mesh_2.geometry} name="mesh_2" />
            </group>
          </group>
        </group>
      </scene>
    </group>
  )
}
